---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reolink-hdd-check
spec:
  replicas: 1
  selector:
    matchLabels:
     app: reolink-hdd-check
  template:
    metadata:
      labels:
        app: reolink-hdd-check
    spec:
      containers:
      - name: reolink-hdd-check
        image: thecase/reolink-hdd-check:latest
        env:
        - name: NVR_PASS
          valueFrom:
            secretKeyRef:
              name: "reolink-nvr"
              key: "password"
        - name: SLACK_WH
          valueFrom:
            secretKeyRef:
              name: "reolink-nvr"
              key: "slack_webhook"
        resources:
           requests:
             cpu: 0.25
           limits:
             cpu: 0.25
